### ISSUE TITLE
unable to prepend Custom Classes 

### ISSUE THREAD

**Issue by raphaelgoetter** [ryanhhhh/headwind#126]
**Describe the bug**
`prependCustomClasses` to `true` should order custom classes before the others.

When I modify the settings to `"headwind.prependCustomClasses": true` (or when I check the chekbox in the extension settings), my custom class is pushed at the end : 

This is what I type : 

```css
class="pre-footer py-40"
```

This is headwind's result  : 

```css
class="py-40 pre-footer"
```

`"headwind.prependCustomClasses": true` and `"headwind.prependCustomClasses": false` produce the exact same result : my custom class is pushed at the end.

**Desktop (please complete the following information):**
 - VScode on MacBook
 - Headwind Version 1.7.0

**Comment by aswinmohanme** [comment]
You have to restart VSCode after the change

**Comment by raphaelgoetter** [comment]
Allright, thank you.
